CREATE DATABASE battleliveredux;

CREATE TABLE user_account 
(id BIGSERIAL PRIMARY KEY NOT NULL, 
username VARCHAR(200) NOT NULL UNIQUE, 
email VARCHAR(200) NOT NULL UNIQUE, 
password VARCHAR(200) NOT NULL
);

CREATE TABLE room
(id BIGSERIAL PRIMARY KEY NOT NULL,
description VARCHAR(200) NOT NULL,
user_id BIGINT NOT NULL UNIQUE, 
FOREIGN KEY (user_id) REFERENCES user_account(id)
);

CREATE TABLE user_connected
(id BIGSERIAL PRIMARY KEY NOT NULL,
room_id BIGINT NOT NULL, 
FOREIGN KEY (id) REFERENCES user_account(id),
FOREIGN KEY (room_id) REFERENCES room(id)
);
